// Generated by CoffeeScript 1.7.1
var LETTER_REGEXP, Question, diacritics;

diacritics = require('diacritics');

LETTER_REGEXP = /\w/g;

Question = (function() {
  Question.prototype.placeholder = '□';

  function Question(string) {
    var _ref;
    _ref = string.split(" \\ "), this.question = _ref[0], this.answer = _ref[1];
    this._answer = this.prepareAnswer(this.answer);
  }

  Question.prototype.prepareAnswer = function(answer) {
    return diacritics.remove(answer).toLowerCase();
  };

  Question.prototype.check = function(answer) {
    return this._answer === this.prepareAnswer(answer);
  };

  Question.prototype.hint = function(level) {
    var answer, answer_length, number_of_letters_to_hide, random_index;
    if (level == null) {
      level = 1;
    }
    switch (level) {
      case 1:
        return this._answer.replace(LETTER_REGEXP, this.placeholder);
      case 2:
        answer = this._answer;
        answer_length = (answer.match(LETTER_REGEXP || [])).length;
        number_of_letters_to_hide = Math.floor(answer_length * 2 / 3);
        while (number_of_letters_to_hide) {
          random_index = Math.floor(Math.random() * answer.length);
          if (LETTER_REGEXP.test(answer[random_index])) {
            answer = answer.substr(0, random_index) + this.placeholder + answer.substr(random_index + 1);
            number_of_letters_to_hide -= 1;
          }
        }
        return answer;
    }
  };

  return Question;

})();

module.exports = Question;
